import { ElectronAPI } from '@electron-toolkit/preload'
import Store from 'secure-electron-store'
export { }; // Make this a module

declare global {

  // 基础配置数据类型
  export interface ConfigData extends Record<string, string> {
    selected: boolean;
    client_secret: string;
    client_id: string;
    sn_host: string;
  }

  // 配置数组类型 - 支持持久化
  export interface ConfigArray extends Array<ConfigData>{
    
  }

  interface Window {
    electron: ElectronAPI
    api: {
      store: Store['preloadBindings']
    }
    env: NodeJS.ProcessEnv
  }

  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).
  const INDEX_VITE_DEV_SERVER_URL: string;
  const INDEX_VITE_NAME: string;

  namespace NodeJS {
    interface Process {
      // Used for hot reload after preload scripts.
      viteDevServers: Record<string, import('vite').ViteDevServer>;
    }
  }

  type VitePluginConfig = ConstructorParameters<typeof import('@electron-forge/plugin-vite').VitePlugin>[0];

  interface VitePluginRuntimeKeys {
    VITE_DEV_SERVER_URL: `${string}_VITE_DEV_SERVER_URL`;
    VITE_NAME: `${string}_VITE_NAME`;
  }
}

declare module 'vite' {
  interface ConfigEnv<K extends keyof VitePluginConfig = keyof VitePluginConfig> {
    root: string;
    forgeConfig: VitePluginConfig;
    forgeConfigSelf: VitePluginConfig[K][number];
  }
}